from __future__ import annotations
from _frozen_importlib import PyIntRect
from collections import namedtuple
from pyclipper._pyclipper import Area
from pyclipper._pyclipper import CleanPolygon
from pyclipper._pyclipper import CleanPolygons
from pyclipper._pyclipper import ClipperException
from pyclipper._pyclipper import ClosedPathsFromPolyTree
from pyclipper._pyclipper import MinkowskiDiff
from pyclipper._pyclipper import MinkowskiSum
from pyclipper._pyclipper import MinkowskiSum2
from pyclipper._pyclipper import OpenPathsFromPolyTree
from pyclipper._pyclipper import Orientation
from pyclipper._pyclipper import PointInPolygon
from pyclipper._pyclipper import PolyTreeToPaths
from pyclipper._pyclipper import PyPolyNode
from pyclipper._pyclipper import Pyclipper
from pyclipper._pyclipper import PyclipperOffset
from pyclipper._pyclipper import ReversePath
from pyclipper._pyclipper import ReversePaths
from pyclipper._pyclipper import SimplifyPolygon
from pyclipper._pyclipper import SimplifyPolygons
from pyclipper._pyclipper import log_action
from pyclipper._pyclipper import scale_from_clipper
from pyclipper._pyclipper import scale_to_clipper
import struct as struct
from . import _pyclipper
from . import _version
__all__ = ['Area', 'CT_DIFFERENCE', 'CT_INTERSECTION', 'CT_UNION', 'CT_XOR', 'CleanPolygon', 'CleanPolygons', 'ClipperException', 'ClosedPathsFromPolyTree', 'ET_CLOSEDLINE', 'ET_CLOSEDPOLYGON', 'ET_OPENBUTT', 'ET_OPENROUND', 'ET_OPENSQUARE', 'JT_MITER', 'JT_ROUND', 'JT_SQUARE', 'MinkowskiDiff', 'MinkowskiSum', 'MinkowskiSum2', 'OpenPathsFromPolyTree', 'Orientation', 'PFT_EVENODD', 'PFT_NEGATIVE', 'PFT_NONZERO', 'PFT_POSITIVE', 'PT_CLIP', 'PT_SUBJECT', 'PointInPolygon', 'PolyTreeToPaths', 'PyIntRect', 'PyPolyNode', 'Pyclipper', 'PyclipperOffset', 'ReversePath', 'ReversePaths', 'SILENT', 'SimplifyPolygon', 'SimplifyPolygons', 'log_action', 'namedtuple', 'scale_from_clipper', 'scale_to_clipper', 'struct']
CT_DIFFERENCE: int = 2
CT_INTERSECTION: int = 0
CT_UNION: int = 1
CT_XOR: int = 3
ET_CLOSEDLINE: int = 1
ET_CLOSEDPOLYGON: int = 0
ET_OPENBUTT: int = 2
ET_OPENROUND: int = 4
ET_OPENSQUARE: int = 3
JT_MITER: int = 2
JT_ROUND: int = 1
JT_SQUARE: int = 0
PFT_EVENODD: int = 0
PFT_NEGATIVE: int = 3
PFT_NONZERO: int = 1
PFT_POSITIVE: int = 2
PT_CLIP: int = 1
PT_SUBJECT: int = 0
SILENT: bool = True
__version__: str = '1.3.0.post6'
